USE [master]
GO
/****** Object:  Database [DBSACH_UIT2T]    Script Date: 01-07-2018 4:45:35 PM ******/
CREATE DATABASE [DBSACH_UIT2T]
GO
ALTER DATABASE [DBSACH_UIT2T] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DBSACH_UIT2T] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DBSACH_UIT2T] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DBSACH_UIT2T] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DBSACH_UIT2T] SET ARITHABORT OFF 
GO
ALTER DATABASE [DBSACH_UIT2T] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DBSACH_UIT2T] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DBSACH_UIT2T] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DBSACH_UIT2T] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DBSACH_UIT2T] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DBSACH_UIT2T] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DBSACH_UIT2T] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DBSACH_UIT2T] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DBSACH_UIT2T] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DBSACH_UIT2T] SET  ENABLE_BROKER 
GO
ALTER DATABASE [DBSACH_UIT2T] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DBSACH_UIT2T] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DBSACH_UIT2T] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DBSACH_UIT2T] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DBSACH_UIT2T] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DBSACH_UIT2T] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DBSACH_UIT2T] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DBSACH_UIT2T] SET RECOVERY FULL 
GO
ALTER DATABASE [DBSACH_UIT2T] SET  MULTI_USER 
GO
ALTER DATABASE [DBSACH_UIT2T] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DBSACH_UIT2T] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DBSACH_UIT2T] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DBSACH_UIT2T] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [DBSACH_UIT2T] SET DELAYED_DURABILITY = DISABLED 
GO
USE [DBSACH_UIT2T]
GO
/****** Object:  Table [dbo].[BAOCAOCONGNO]    Script Date: 01-07-2018 4:45:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BAOCAOCONGNO](
	[MaBaoCaoCongNo] [int] IDENTITY(1,1) NOT NULL,
	[Thang] [datetime2](7) NULL,
	[NgayLap] [datetime2](7) NULL,
 CONSTRAINT [PK_BAOCAOCONGNO] PRIMARY KEY CLUSTERED 
(
	[MaBaoCaoCongNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[BAOCAOTON]    Script Date: 01-07-2018 4:45:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BAOCAOTON](
	[MaBaoCaoTon] [int] IDENTITY(1,1) NOT NULL,
	[Thang] [datetime2](7) NULL,
	[NgayLap] [datetime2](7) NULL,
 CONSTRAINT [PK_BAOCAOTON] PRIMARY KEY CLUSTERED 
(
	[MaBaoCaoTon] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[CHITIETBAOCAOCONGNO]    Script Date: 01-07-2018 4:45:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHITIETBAOCAOCONGNO](
	[MaChiTietBaoCaoCongNo] [int] IDENTITY(1,1) NOT NULL,
	[MaBaoCaoCongNo] [int] NULL,
	[MaKhachHang] [int] NULL,
	[NoDau] [float] NULL,
	[PhatSinh] [float] NULL,
	[NoCuoi] [float] NULL,
 CONSTRAINT [PK_CHITIETBAOCAOCONGNO] PRIMARY KEY CLUSTERED 
(
	[MaChiTietBaoCaoCongNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[CHITIETBAOCAOTON]    Script Date: 01-07-2018 4:45:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHITIETBAOCAOTON](
	[MaChiTietBaoCaoTon] [int] IDENTITY(1,1) NOT NULL,
	[MaBaoCaoTon] [int] NULL,
	[MaSach] [int] NULL,
	[TonDau] [int] NULL,
	[PhatSinh] [int] NULL,
	[TonCuoi] [int] NULL,
 CONSTRAINT [PK_CHITIETBAOCAOTON] PRIMARY KEY CLUSTERED 
(
	[MaChiTietBaoCaoTon] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[CHITIETHOADON]    Script Date: 01-07-2018 4:45:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHITIETHOADON](
	[MaChiTietHoaDon] [int] IDENTITY(1,1) NOT NULL,
	[MaHoaDon] [int] NULL,
	[MaSach] [int] NULL,
	[SoLuongBan] [int] NULL,
	[DonGiaBan] [float] NULL,
 CONSTRAINT [PK_CHITIETHOADON] PRIMARY KEY CLUSTERED 
(
	[MaChiTietHoaDon] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[CHITIETPHIEUNHAP]    Script Date: 01-07-2018 4:45:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHITIETPHIEUNHAP](
	[MaChiTietPhieuNhap] [int] IDENTITY(1,1) NOT NULL,
	[MaPhieuNhap] [int] NULL,
	[MaSach] [int] NULL,
	[SoLuongNhap] [int] NULL,
 CONSTRAINT [PK_CHITIETPHIEUNHAP] PRIMARY KEY CLUSTERED 
(
	[MaChiTietPhieuNhap] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[DANGNHAP]    Script Date: 01-07-2018 4:45:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DANGNHAP](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[TenDangNhap] [nvarchar](100) NULL,
	[MatKhau] [nvarchar](50) NULL,
 CONSTRAINT [PK_DANGNHAP] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[HOADON]    Script Date: 01-07-2018 4:45:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOADON](
	[MaHoaDon] [int] IDENTITY(1,1) NOT NULL,
	[NgayLapHoaDon] [datetime2](7) NULL,
	[MaKhachHang] [int] NULL,
 CONSTRAINT [PK_HOADON] PRIMARY KEY CLUSTERED 
(
	[MaHoaDon] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[KHACHHANG]    Script Date: 01-07-2018 4:45:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACHHANG](
	[MaKhachHang] [int] IDENTITY(1,1) NOT NULL,
	[HoTenKhachHang] [nvarchar](100) NULL,
	[DiaChi] [nvarchar](200) NULL,
	[DienThoai] [nvarchar](20) NULL,
	[Email] [nvarchar](100) NULL,
	[TienNo] [float] NULL,
 CONSTRAINT [PK_KHACHHANG] PRIMARY KEY CLUSTERED 
(
	[MaKhachHang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PHIEUNHAP]    Script Date: 01-07-2018 4:45:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHIEUNHAP](
	[MaPhieuNhap] [int] IDENTITY(1,1) NOT NULL,
	[NgayNhap] [datetime2](7) NULL,
 CONSTRAINT [PK_PHIEUNHAP] PRIMARY KEY CLUSTERED 
(
	[MaPhieuNhap] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PHIEUTHUTIEN]    Script Date: 01-07-2018 4:45:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHIEUTHUTIEN](
	[MaPhieuThu] [int] IDENTITY(1,1) NOT NULL,
	[MaKhachHang] [int] NULL,
	[NgayThuTien] [datetime2](7) NULL,
	[SoTienThu] [float] NULL,
 CONSTRAINT [PK_PHIEUTHUTIEN] PRIMARY KEY CLUSTERED 
(
	[MaPhieuThu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[SACH]    Script Date: 01-07-2018 4:45:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SACH](
	[MaSach] [int] IDENTITY(1,1) NOT NULL,
	[TenSach] [nvarchar](200) NULL,
	[TheLoai] [nvarchar](50) NULL,
	[TacGia] [nvarchar](100) NULL,
	[SoLuongTon] [int] NULL,
	[DonGia] [float] NULL,
 CONSTRAINT [PK_SACH] PRIMARY KEY CLUSTERED 
(
	[MaSach] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[THAMSO]    Script Date: 01-07-2018 4:45:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THAMSO](
	[SoLuongNhapToiThieu] [int] NOT NULL,
	[SoLuongTonToiDa] [int] NOT NULL,
	[SoLuongTonToiThieu] [int] NOT NULL,
	[SoTienNoToiDa] [float] NOT NULL,
	[SuDungQD4] [bit] NOT NULL
) ON [PRIMARY]

GO
SET IDENTITY_INSERT [dbo].[DANGNHAP] ON 

INSERT [dbo].[DANGNHAP] ([id], [TenDangNhap], [MatKhau]) VALUES (1, N'admin', N'BBB2CA48225EFB207E0EC1CD9F2877BD')
SET IDENTITY_INSERT [dbo].[DANGNHAP] OFF
SET IDENTITY_INSERT [dbo].[KHACHHANG] ON 

INSERT [dbo].[KHACHHANG] ([MaKhachHang], [HoTenKhachHang], [DiaChi], [DienThoai], [Email], [TienNo]) VALUES (1, N'Nguyễn Huỳnh Thanh Tâm', N'TP.HCM', N'01223632954', N'16521062@gm.uit.edu.vn', 0)
INSERT [dbo].[KHACHHANG] ([MaKhachHang], [HoTenKhachHang], [DiaChi], [DienThoai], [Email], [TienNo]) VALUES (2, N'Đặng Minh Tiến', N'Bến Tre', N'0961014106', N'dangminhtien06@gmail.com', 0)
SET IDENTITY_INSERT [dbo].[KHACHHANG] OFF
SET IDENTITY_INSERT [dbo].[SACH] ON 

INSERT [dbo].[SACH] ([MaSach], [TenSach], [TheLoai], [TacGia], [SoLuongTon], [DonGia]) VALUES (1, N'Nhà Lãnh Đạo Không Chức Danh', N'Kinh tế', N'Robin Sharma', 0, 80000)
INSERT [dbo].[SACH] ([MaSach], [TenSach], [TheLoai], [TacGia], [SoLuongTon], [DonGia]) VALUES (2, N'P.Kotler Tiếp thị 4.0', N'Kinh tế', N'Nguyễn Khoa Hồng Thành', 0, 79000)
INSERT [dbo].[SACH] ([MaSach], [TenSach], [TheLoai], [TacGia], [SoLuongTon], [DonGia]) VALUES (3, N'Qua Pixar Là Vô Cực', N'Kinh tế', N'Lawrence Levy', 0, 150000)
INSERT [dbo].[SACH] ([MaSach], [TenSach], [TheLoai], [TacGia], [SoLuongTon], [DonGia]) VALUES (4, N'Cẩm Nang Tự Học IELTS', N'Ngoại ngữ', N'Kiên Trần', 0, 90000)
INSERT [dbo].[SACH] ([MaSach], [TenSach], [TheLoai], [TacGia], [SoLuongTon], [DonGia]) VALUES (5, N'Đề Kiểm Tra Tiếng Anh Lớp 7', N'Ngoại ngữ', N'Trần Mạnh Tường', 0, 40800)
INSERT [dbo].[SACH] ([MaSach], [TenSach], [TheLoai], [TacGia], [SoLuongTon], [DonGia]) VALUES (6, N'3000 Từ Vựng Tiếng Anh Thông Dụng Nhất', N'Ngoại ngữ', N'The Windy', 0, 58000)
INSERT [dbo].[SACH] ([MaSach], [TenSach], [TheLoai], [TacGia], [SoLuongTon], [DonGia]) VALUES (7, N'Tự Học Tiếng Hàn Dành Cho Người Mới Bắt Đầu', N'Ngoại ngữ', N'NXB Thời Đại', 0, 72000)
SET IDENTITY_INSERT [dbo].[SACH] OFF
INSERT [dbo].[THAMSO] ([SoLuongNhapToiThieu], [SoLuongTonToiDa], [SoLuongTonToiThieu], [SoTienNoToiDa], [SuDungQD4]) VALUES (150, 300, 20, 20000, 1)
ALTER TABLE [dbo].[CHITIETBAOCAOCONGNO]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETBAOCAOCONGNO_BAOCAOCONGNO] FOREIGN KEY([MaBaoCaoCongNo])
REFERENCES [dbo].[BAOCAOCONGNO] ([MaBaoCaoCongNo])
GO
ALTER TABLE [dbo].[CHITIETBAOCAOCONGNO] CHECK CONSTRAINT [FK_CHITIETBAOCAOCONGNO_BAOCAOCONGNO]
GO
ALTER TABLE [dbo].[CHITIETBAOCAOCONGNO]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETBAOCAOCONGNO_KHACHHANG] FOREIGN KEY([MaKhachHang])
REFERENCES [dbo].[KHACHHANG] ([MaKhachHang])
GO
ALTER TABLE [dbo].[CHITIETBAOCAOCONGNO] CHECK CONSTRAINT [FK_CHITIETBAOCAOCONGNO_KHACHHANG]
GO
ALTER TABLE [dbo].[CHITIETBAOCAOTON]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETBAOCAOTON_BAOCAOTON] FOREIGN KEY([MaBaoCaoTon])
REFERENCES [dbo].[BAOCAOTON] ([MaBaoCaoTon])
GO
ALTER TABLE [dbo].[CHITIETBAOCAOTON] CHECK CONSTRAINT [FK_CHITIETBAOCAOTON_BAOCAOTON]
GO
ALTER TABLE [dbo].[CHITIETBAOCAOTON]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETBAOCAOTON_SACH] FOREIGN KEY([MaSach])
REFERENCES [dbo].[SACH] ([MaSach])
GO
ALTER TABLE [dbo].[CHITIETBAOCAOTON] CHECK CONSTRAINT [FK_CHITIETBAOCAOTON_SACH]
GO
ALTER TABLE [dbo].[CHITIETHOADON]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETHOADON_HOADON] FOREIGN KEY([MaHoaDon])
REFERENCES [dbo].[HOADON] ([MaHoaDon])
GO
ALTER TABLE [dbo].[CHITIETHOADON] CHECK CONSTRAINT [FK_CHITIETHOADON_HOADON]
GO
ALTER TABLE [dbo].[CHITIETHOADON]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETHOADON_SACH] FOREIGN KEY([MaSach])
REFERENCES [dbo].[SACH] ([MaSach])
GO
ALTER TABLE [dbo].[CHITIETHOADON] CHECK CONSTRAINT [FK_CHITIETHOADON_SACH]
GO
ALTER TABLE [dbo].[CHITIETPHIEUNHAP]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETPHIEUNHAP_PHIEUNHAP] FOREIGN KEY([MaPhieuNhap])
REFERENCES [dbo].[PHIEUNHAP] ([MaPhieuNhap])
GO
ALTER TABLE [dbo].[CHITIETPHIEUNHAP] CHECK CONSTRAINT [FK_CHITIETPHIEUNHAP_PHIEUNHAP]
GO
ALTER TABLE [dbo].[CHITIETPHIEUNHAP]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETPHIEUNHAP_SACH] FOREIGN KEY([MaSach])
REFERENCES [dbo].[SACH] ([MaSach])
GO
ALTER TABLE [dbo].[CHITIETPHIEUNHAP] CHECK CONSTRAINT [FK_CHITIETPHIEUNHAP_SACH]
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD  CONSTRAINT [FK_HOADON_KHACHHANG] FOREIGN KEY([MaKhachHang])
REFERENCES [dbo].[KHACHHANG] ([MaKhachHang])
GO
ALTER TABLE [dbo].[HOADON] CHECK CONSTRAINT [FK_HOADON_KHACHHANG]
GO
ALTER TABLE [dbo].[PHIEUTHUTIEN]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUTHUTIEN_KHACHHANG] FOREIGN KEY([MaKhachHang])
REFERENCES [dbo].[KHACHHANG] ([MaKhachHang])
GO
ALTER TABLE [dbo].[PHIEUTHUTIEN] CHECK CONSTRAINT [FK_PHIEUTHUTIEN_KHACHHANG]
GO




DBCC CHECKIDENT('CHITIETPHIEUNHAP', RESEED, 0)

GO
DBCC CHECKIDENT('PHIEUNHAP', RESEED, 0)

GO
DBCC CHECKIDENT('HOADON', RESEED, 0)

GO
DBCC CHECKIDENT('CHITIETHOADON', RESEED, 0)

GO
DBCC CHECKIDENT('PHIEUTHUTIEN', RESEED, 0)

GO
DBCC CHECKIDENT('BAOCAOCONGNO', RESEED, 0)
GO
DBCC CHECKIDENT('BAOCAOTON', RESEED, 0)
GO
DBCC CHECKIDENT('CHITIETBAOCAOCONGNO', RESEED, 0)
GO
DBCC CHECKIDENT('CHITIETBAOCAOTON', RESEED, 0)



GO


USE [master]
GO
ALTER DATABASE [DBSACH_UIT2T] SET  READ_WRITE 
GO
